# Generated by Django 6.0.1 on 2026-02-02 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positive for credit, Negative for debit')),
                ('transaction_type', models.CharField(choices=[('INITIAL_GRANT', 'Initial Grant'), ('SESSION_PAYMENT', 'Session Payment'), ('BOUNTY_REWARD', 'Bounty Reward'), ('PENALTY', 'Penalty')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.wallet')),
            ],
        ),
    ]
