# Generated by Django 6.0.1 on 2026-02-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('INITIAL_GRANT', 'Initial Grant'), ('SESSION_PAYMENT', 'Session Payment'), ('BOUNTY_REWARD', 'Bounty Reward'), ('PENALTY', 'Penalty'), ('TAX', 'Tax'), ('DONATION', 'Donation')], max_length=50),
        ),
    ]
