# Generated by Django 6.0.1 on 2026-02-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningrequestpost',
            old_name='is_just_learning',
            new_name='bounty_mode',
        ),
        migrations.RenameField(
            model_name='learningrequestpost',
            old_name='user',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='learningrequestpost',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='learningrequestpost',
            old_name='want_to_learn',
            new_name='topic_to_learn',
        ),
        migrations.RenameField(
            model_name='learningrequestpost',
            old_name='can_teach',
            new_name='topic_to_teach',
        ),
        migrations.AddField(
            model_name='learningrequestpost',
            name='learning_only_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='learningrequestpost',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Active', max_length=20),
        ),
    ]
