# Generated by Django 6.0.1 on 2026-02-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_rename_is_just_learning_learningrequestpost_bounty_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bounty_mode_active', models.BooleanField(default=False)),
            ],
        ),
    ]
