# Generated by Django 6.0.1 on 2026-02-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='last_support_claim',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
